export const EXTENDED_WIDGET_STYLE_DEFAULTS = {
  show_widget_title: true,
  default_sorting: "newest",
  reviews_per_page: 10,
  widget_theme: "standard",
  layout_columns: 3,
  star_color: "#F59E0B",
  button_color: "#F59E0B",
  button_text_color: "#131720",
  show_review_date: true,
  show_verified_badge: true,
  show_product_name: true,
  write_review_button_text: "Write a review",
  reply_author_name: "Store Owner",
  show_search_bar: false,
  show_rating_filters: false,
  expanded_media_gallery: false,
  image_style: "rounded",
  reviewer_name_format: "full",
  show_reviewer_location: false,
};

const pickExtendedStyles = (style = {}) => ({
  show_widget_title: style.show_widget_title !== false,
  default_sorting: style.default_sorting || "newest",
  reviews_per_page: Number(style.reviews_per_page) || 10,
  widget_theme: style.widget_theme || "standard",
  layout_columns: Number(style.layout_columns) || 3,
  star_color: style.star_color || style.primary_color || "#F59E0B",
  button_color: style.button_color || style.primary_color || "#F59E0B",
  button_text_color: style.button_text_color || "#131720",
  show_review_date: style.show_review_date !== false,
  show_verified_badge: style.show_verified_badge !== false,
  show_product_name: style.show_product_name !== false,
  write_review_button_text: style.write_review_button_text || "Write a review",
  reply_author_name: style.reply_author_name || "Store Owner",
  show_search_bar: !!style.show_search_bar,
  show_rating_filters: !!style.show_rating_filters,
  expanded_media_gallery: !!style.expanded_media_gallery,
  image_style: style.image_style || "rounded",
  reviewer_name_format: style.reviewer_name_format || "full",
  show_reviewer_location: !!style.show_reviewer_location,
});

export { pickExtendedStyles };
