<?php

/**
 * Hyoka
 *
 * @package   Hyoka
 * @author    Hyoka
 * @license   GPL-2.0-or-later
 * @link      https://hyoka.com
 */

namespace Hyoka\App\Helper;

use Hyoka\Woocommerce\Email\EmailSender;

defined('ABSPATH') || exit;

/**
 * Enqueues plugin styles and attaches dynamic CSS through wp_add_inline_style().
 *
 * Dynamic CSS follows the WordPress pattern:
 * 1. Sanitize at the builder site with core sanitize_hex_color() and
 *    Wp::fontStackCss() (FONT_STACKS allow-list via sanitizeFontKey()).
 * 2. Generate CSS in get*CssVariablesBlock() builders from those tokens only.
 * 3. Escape with wp_strip_all_tags() (WordPress has no esc_css()) and pass to wp_add_inline_style().
 *
 * Validation belongs in the generators; output uses wp_strip_all_tags() for Plugin Check.
 */
class Assets
{
    public const HANDLE_WIDGET_STYLE   = 'hyoka-widget-style';
    public const HANDLE_FRONTEND_STYLE = 'hyoka-frontend-style';
    public const HANDLE_REVIEW_FORM    = 'hyoka-review-form';
    public const HANDLE_WIDGET_SCRIPT  = 'hyoka-widget-script';
    public const HANDLE_INVITE_EMAIL   = 'hyoka-invite-email';
    public const HANDLE_REVIEW_INVITE  = 'hyoka-review-invite';
    public const HANDLE_MEDIA_UPLOAD   = 'hyoka-media-upload';
    public const HANDLE_REACT_APP      = 'hyoka-react-app';
    public const HANDLE_ADMIN_STYLE    = 'hyoka-admin-style';
    public const HANDLE_EMAIL_STYLE    = 'hyoka-email-style';

    private static function url(string $relative_path): string
    {
        return plugins_url($relative_path, HYOKA_PLUGIN_FILE);
    }

    private static function version(?string $version = null): string
    {
        return $version !== null && $version !== '' ? $version : HYOKA_VERSION;
    }

    /**
     * Attach internally generated CSS variables to an already enqueued stylesheet.
     *
     * WordPress has no esc_css(). Using esc_html()/esc_attr() would corrupt CSS
     * (e.g. quoted font stacks). Safety is enforced by:
     * 1. CSS builders only interpolating validated tokens
     * 2. wp_strip_all_tags() at output (Plugin Check–accepted CSS escape)
     *
     * Builders use core sanitize_hex_color(), Wp::fontStackCss() (FONT_STACKS
     * allow-list), sanitizeCssLength(), sanitizeCssFontWeight(), absint clamps,
     * and enum whitelists.
     * Arbitrary / user-authored CSS is not accepted or stored (custom_css removed).
     *
     * @param string $handle Registered stylesheet handle.
     * @param string $css    CSS generated by the plugin's internal CSS builder methods.
     */
    private static function attachInlineCss(string $handle, string $css): void
    {
        if ($css === '') {
            return;
        }

        // wp_strip_all_tags() is the WordPress.org–accepted way to escape CSS for
        // wp_add_inline_style() (there is no esc_css()). Values were already sanitized
        // by the CSS builders (hex colors, lengths, allowlisted font stacks, enums).
        wp_add_inline_style($handle, wp_strip_all_tags($css));
    }

    /**
     * Storefront widget + review-form styles (product pages / shortcodes).
     *
     * @param string $version         Asset version string.
     * @param string $widget_vars_css Concatenated Wp::getWidgetCssVariablesBlock() output.
     */
    public static function enqueueStorefrontStyles(string $version = '', string $widget_vars_css = ''): void
    {
        $version = self::version($version !== '' ? $version : null);

        wp_enqueue_style(
            self::HANDLE_WIDGET_STYLE,
            self::url('assets/css/widget.css'),
            [],
            $version
        );
        wp_enqueue_style(
            self::HANDLE_FRONTEND_STYLE,
            self::url('assets/css/frontend.css'),
            [],
            $version
        );
        wp_enqueue_style(
            self::HANDLE_REVIEW_FORM,
            self::url('assets/css/review-form.css'),
            [self::HANDLE_FRONTEND_STYLE],
            $version
        );

        self::attachInlineCss(self::HANDLE_WIDGET_STYLE, $widget_vars_css);

        $form_vars = SubmissionFormRender::getFormCssVariablesBlock(EmailSender::getSettings());
        self::attachInlineCss(self::HANDLE_REVIEW_FORM, $form_vars);
    }

    /**
     * Storefront interactive widget script.
     *
     * @param array<string, mixed> $localize
     */
    public static function enqueueStorefrontScript(string $version, array $localize): void
    {
        wp_enqueue_script(
            self::HANDLE_WIDGET_SCRIPT,
            self::url('assets/js/widget.js'),
            ['jquery'],
            self::version($version),
            true
        );
        wp_localize_script(self::HANDLE_WIDGET_SCRIPT, 'hyokaData', $localize);
    }

    /**
     * Email invite review page (standalone HTML shell).
     *
     * @param array<string, mixed> $settings EmailSender settings (theme tokens).
     * @param array<string, mixed> $localize Data for hyokaInviteReview.
     */
    public static function enqueueInvitePage(array $settings, array $localize): void
    {
        self::enqueueEmailShellStyles($settings);

        wp_enqueue_script(
            self::HANDLE_REVIEW_INVITE,
            self::url('assets/js/review-invite-front.js'),
            ['jquery'],
            HYOKA_VERSION,
            false
        );
        wp_localize_script(self::HANDLE_REVIEW_INVITE, 'hyokaInviteReview', $localize);
    }

    /**
     * Media-upload follow-up page (standalone HTML shell).
     *
     * @param array<string, mixed> $settings EmailSender settings (theme tokens).
     * @param array<string, mixed> $localize Data for hyokaMediaUpload.
     */
    public static function enqueueMediaUploadPage(array $settings, array $localize): void
    {
        self::enqueueEmailShellStyles($settings);

        wp_enqueue_script(
            self::HANDLE_MEDIA_UPLOAD,
            self::url('assets/js/media-upload-front.js'),
            ['jquery'],
            HYOKA_VERSION,
            false
        );
        wp_localize_script(self::HANDLE_MEDIA_UPLOAD, 'hyokaMediaUpload', $localize);
    }

    /**
     * Admin React app + shared preview styles.
     *
     * @param array<string, mixed> $localize Data for hyokaData.
     */
    public static function enqueueAdminApp(string $bundle_file, array $localize): void
    {
        wp_enqueue_script(
            self::HANDLE_REACT_APP,
            self::url('admin-ui/dist/' . $bundle_file),
            ['wp-element'],
            HYOKA_VERSION,
            true
        );
        wp_localize_script(self::HANDLE_REACT_APP, 'hyokaData', $localize);

        wp_enqueue_style(
            self::HANDLE_WIDGET_STYLE,
            self::url('assets/css/widget.css'),
            [],
            HYOKA_VERSION
        );
        wp_enqueue_style(
            self::HANDLE_FRONTEND_STYLE,
            self::url('assets/css/frontend.css'),
            [],
            HYOKA_VERSION
        );
        wp_enqueue_style(
            self::HANDLE_REVIEW_FORM,
            self::url('assets/css/review-form.css'),
            [self::HANDLE_FRONTEND_STYLE],
            HYOKA_VERSION
        );
        $form_vars = SubmissionFormRender::getFormCssVariablesBlock(EmailSender::getSettings());
        self::attachInlineCss(self::HANDLE_REVIEW_FORM, $form_vars);
        wp_enqueue_style(
            self::HANDLE_ADMIN_STYLE,
            self::url('admin-ui/dist/hyoka.css'),
            [],
            HYOKA_VERSION
        );
        wp_enqueue_style(
            self::HANDLE_EMAIL_STYLE,
            self::url('assets/css/email.css'),
            [],
            HYOKA_VERSION
        );
    }

    /**
     * Shared email.css + theme CSS variables for invite/media shells.
     *
     * @param array<string, mixed> $settings
     */
    private static function enqueueEmailShellStyles(array $settings): void
    {
        wp_enqueue_style(
            self::HANDLE_INVITE_EMAIL,
            self::url('assets/css/email.css'),
            [],
            HYOKA_VERSION
        );

        $vars = SubmissionFormRender::getEmailPageCssVariablesBlock($settings);
        self::attachInlineCss(self::HANDLE_INVITE_EMAIL, $vars);
    }
}
